import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { FILL_VALUE_HASH_SCHEMA, FILL_VALUE_HASH_VERSION, UnpairedSurrogateError, fillValueHash } from "../src/fill/hash";

// The ONE shared S5 vector set, generated by tools/gen_fill_hash_vectors.py
// from the Python canonical implementation and loaded here unmodified.
const vectorsPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "tests", "fixtures",
  "fill", "hash_vectors.json");

interface Vector { name: string; category: string; input: string; expected?: string; error?: string }
const data = JSON.parse(readFileSync(vectorsPath, "utf8")) as {
  hash_function: string; vectors: Vector[]; equivalence_groups: string[][];
};

describe("fillValueHash matches the shared Python-generated vectors (spec §7.5, S5)", () => {
  it("is generated by the Python canonical function", () => {
    expect(data.hash_function).toBe("product.fill_hash.fill_value_hash");
    expect(data.vectors.filter((v) => v.expected).length).toBeGreaterThanOrEqual(20);
  });

  for (const vector of data.vectors.filter((v) => v.expected !== undefined)) {
    it(`hashes ${vector.name} (${vector.category}) exactly as Python`, async () => {
      expect(await fillValueHash(vector.input)).toBe(vector.expected);
    });
  }

  for (const vector of data.vectors.filter((v) => v.error !== undefined)) {
    it(`rejects ${vector.name} exactly as Python`, async () => {
      expect(vector.error).toBe("unpaired_surrogate");
      await expect(fillValueHash(vector.input)).rejects.toBeInstanceOf(UnpairedSurrogateError);
    });
  }

  it("hashes every equivalence group identically", async () => {
    const byName = new Map(data.vectors.map((v) => [v.name, v]));
    for (const group of data.equivalence_groups) {
      const hashes = await Promise.all(group.map((name) => fillValueHash(byName.get(name)!.input)));
      expect(new Set(hashes).size, group.join("=")).toBe(1);
    }
  });

  it("uses the same schema identifiers as Python", () => {
    expect([FILL_VALUE_HASH_SCHEMA, FILL_VALUE_HASH_VERSION]).toEqual(["fill-rendered-value", "v1"]);
  });
});
