"""Bundle 7 migrations (spec §23.1): one per introducing task, each with a
SQLite and a PostgreSQL body. A migration is never edited once committed."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable


@dataclass(frozen=True)
class Migration:
    id: str
    sqlite: Callable[[Any], None]
    postgres: Callable[[Any], None]
    disable_foreign_keys: bool = False


def _statements(conn, script: str) -> None:
    for statement in script.split(";"):
        if statement.strip():
            conn.execute(statement)


def sqlite_append_only(conn, table: str) -> None:
    message = f"{table} is append-only audit history"
    for event in ("UPDATE", "DELETE"):
        conn.execute(
            f"CREATE TRIGGER {table}_append_only_{event.lower()} BEFORE {event} ON {table} "
            f"BEGIN SELECT RAISE(ABORT, '{message}'); END"
        )


def postgres_append_only(conn, table: str) -> None:
    message = f"{table} is append-only audit history"
    for event in ("UPDATE", "DELETE"):
        conn.execute(
            f'CREATE TRIGGER "{table}_append_only_{event.lower()}" BEFORE {event} ON "{table}" '
            f"FOR EACH ROW EXECUTE FUNCTION jobsearch_raise('{message}')"
        )


# ---- 022_storage (Task 4): profile sources in the database; per-account
# user-profile versions (no cross-tenant content dedupe, spec H6) ----------

_PROFILE_SOURCE_REVISIONS_COLUMNS = """
    id TEXT NOT NULL UNIQUE,
    account_id TEXT NOT NULL REFERENCES accounts(id),
    source_path TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision >= 1),
    content TEXT,
    sha256 TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (account_id, source_path, revision),
    CHECK ((content IS NULL) = (sha256 IS NULL))
"""


def _version_accounts(conn) -> dict[str, str]:
    """version id -> owning account, from every table that references a version."""
    owners: dict[str, set[str]] = {}
    queries = (
        "SELECT h.version_id AS v, s.account_id AS a FROM search_workspace_user_profile_history h "
        "JOIN search_workspaces s ON s.id = h.search_workspace_id",
        "SELECT h.previous_version_id AS v, s.account_id AS a FROM search_workspace_user_profile_history h "
        "JOIN search_workspaces s ON s.id = h.search_workspace_id WHERE h.previous_version_id IS NOT NULL",
        "SELECT p.current_version_id AS v, s.account_id AS a FROM search_workspace_user_profiles p "
        "JOIN search_workspaces s ON s.id = p.search_workspace_id",
        "SELECT r.user_profile_version_id AS v, s.account_id AS a FROM discovery_runs r "
        "JOIN search_workspaces s ON s.id = r.search_workspace_id",
        "SELECT version_id AS v, 'account_local' AS a FROM current_user_profile",
    )
    for query in queries:
        for row in conn.execute(query).fetchall():
            owners.setdefault(row["v"], set()).add(row["a"])
    result: dict[str, str] = {}
    for version_id, accounts in owners.items():
        if len(accounts) > 1:
            raise RuntimeError(
                f"user profile version {version_id} is shared by accounts {sorted(accounts)}; "
                "022_storage cannot assign it to one owner")
        result[version_id] = next(iter(accounts))
    return result


def _backfill_version_accounts(conn) -> None:
    owners = _version_accounts(conn)
    for row in conn.execute("SELECT id FROM user_profile_versions").fetchall():
        conn.execute("UPDATE user_profile_versions SET account_id = ? WHERE id = ?",
                     (owners.get(row["id"], "account_local"), row["id"]))


def _storage_sqlite(conn) -> None:
    conn.execute(f"CREATE TABLE profile_source_revisions (seq INTEGER PRIMARY KEY AUTOINCREMENT,"
                 f"{_PROFILE_SOURCE_REVISIONS_COLUMNS})")
    sqlite_append_only(conn, "profile_source_revisions")
    owners = _version_accounts(conn)
    conn.execute("""
        CREATE TABLE user_profile_versions_022 (
            id TEXT PRIMARY KEY,
            content_id TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            created_at TEXT NOT NULL,
            account_id TEXT NOT NULL REFERENCES accounts(id),
            UNIQUE (account_id, content_id)
        )""")
    for row in conn.execute("SELECT id, content_id, payload_json, created_at FROM user_profile_versions").fetchall():
        conn.execute(
            "INSERT INTO user_profile_versions_022 (id, content_id, payload_json, created_at, account_id) "
            "VALUES (?, ?, ?, ?, ?)",
            (row["id"], row["content_id"], row["payload_json"], row["created_at"],
             owners.get(row["id"], "account_local")))
    conn.execute("DROP TABLE user_profile_versions")
    conn.execute("ALTER TABLE user_profile_versions_022 RENAME TO user_profile_versions")


def _storage_postgres(conn) -> None:
    conn.execute(f"CREATE TABLE profile_source_revisions (seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                 f"{_PROFILE_SOURCE_REVISIONS_COLUMNS.replace('revision INTEGER', 'revision BIGINT')})")
    postgres_append_only(conn, "profile_source_revisions")
    conn.execute("ALTER TABLE user_profile_versions ADD COLUMN account_id TEXT")
    _backfill_version_accounts(conn)
    _statements(conn, """
        ALTER TABLE user_profile_versions ALTER COLUMN account_id SET NOT NULL;
        ALTER TABLE user_profile_versions DROP CONSTRAINT user_profile_versions_content_id_key;
        ALTER TABLE user_profile_versions ADD CONSTRAINT user_profile_versions_account_content_key
            UNIQUE (account_id, content_id);
        ALTER TABLE user_profile_versions ADD CONSTRAINT fk_user_profile_versions_account
            FOREIGN KEY (account_id) REFERENCES accounts (id)
    """)


BUNDLE7_MIGRATIONS: list[Migration] = [
    Migration("022_storage", sqlite=_storage_sqlite, postgres=_storage_postgres, disable_foreign_keys=True),
]


# ---- shared DDL helpers for Bundle 7 tables --------------------------------
# New Bundle 7 tables carry no synthetic PostgreSQL "rowid": nothing orders
# them by insertion rowid (append-only tables use their seq column).

SEQ = {"sqlite": "seq INTEGER PRIMARY KEY AUTOINCREMENT",
       "postgres": "seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"}


def _ddl(conn, dialect: str, script: str) -> None:
    _statements(conn, script.replace("{SEQ}", SEQ[dialect]))


def _append_only(conn, dialect: str, *tables: str) -> None:
    for table in tables:
        (sqlite_append_only if dialect == "sqlite" else postgres_append_only)(conn, table)


# ---- 023_identity (Task 7): users, sessions, email tokens, staff roles,
# legal acceptances, rate limits (spec §6.1) --------------------------------

_IDENTITY_DDL = """
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email_normalized TEXT NOT NULL UNIQUE,
    email_display TEXT NOT NULL,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DELETION_REQUESTED', 'PURGED')),
    email_verified_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_login_at TEXT,
    password_changed_at TEXT
);
CREATE TABLE user_identities (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    provider TEXT NOT NULL CHECK (provider IN ('password')),
    secret_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    revoked_at TEXT
);
CREATE UNIQUE INDEX idx_user_identities_live ON user_identities(user_id, provider) WHERE revoked_at IS NULL;
CREATE TABLE account_memberships (
    account_id TEXT NOT NULL REFERENCES accounts(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    role TEXT NOT NULL CHECK (role IN ('OWNER')),
    created_at TEXT NOT NULL,
    revoked_at TEXT,
    PRIMARY KEY (account_id, user_id)
);
CREATE INDEX idx_account_memberships_user ON account_memberships(user_id);
CREATE TABLE web_sessions (
    id_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    kind TEXT NOT NULL CHECK (kind IN ('CUSTOMER', 'STAFF')),
    created_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    idle_expires_at TEXT NOT NULL,
    absolute_expires_at TEXT NOT NULL,
    revoked_at TEXT,
    revoke_reason TEXT,
    ip_hash TEXT,
    user_agent_summary TEXT
);
CREATE INDEX idx_web_sessions_user ON web_sessions(user_id);
CREATE TABLE email_tokens (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    purpose TEXT NOT NULL CHECK (purpose IN ('VERIFY_EMAIL', 'PASSWORD_RESET', 'EMAIL_CHANGE')),
    token_hash TEXT NOT NULL UNIQUE,
    new_email_normalized TEXT,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    consumed_at TEXT
);
CREATE TABLE platform_role_assignments (
    {SEQ},
    id TEXT NOT NULL UNIQUE,
    user_id TEXT NOT NULL REFERENCES users(id),
    role TEXT NOT NULL CHECK (role IN ('SUPPORT', 'OPERATIONS', 'BILLING', 'ADMIN')),
    action TEXT NOT NULL CHECK (action IN ('GRANT', 'REVOKE')),
    actor_user_id TEXT REFERENCES users(id),
    reason TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE TABLE staff_totp (
    user_id TEXT PRIMARY KEY REFERENCES users(id),
    secret_encrypted TEXT NOT NULL,
    confirmed_at TEXT
);
CREATE TABLE legal_documents (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('TERMS', 'PRIVACY')),
    version TEXT NOT NULL,
    published_at TEXT NOT NULL,
    content_sha256 TEXT NOT NULL,
    UNIQUE (kind, version)
);
CREATE TABLE legal_acceptances (
    {SEQ},
    id TEXT NOT NULL UNIQUE,
    user_id TEXT NOT NULL REFERENCES users(id),
    legal_document_id TEXT NOT NULL REFERENCES legal_documents(id),
    accepted_at TEXT NOT NULL,
    ip_hash TEXT
);
CREATE TABLE rate_limit_buckets (
    key TEXT NOT NULL,
    window_start TEXT NOT NULL,
    count INTEGER NOT NULL CHECK (count >= 0),
    PRIMARY KEY (key, window_start)
);
ALTER TABLE accounts ADD COLUMN kind TEXT NOT NULL DEFAULT 'candidate' CHECK (kind IN ('candidate', 'local'));
ALTER TABLE accounts ADD COLUMN status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETION_REQUESTED', 'PURGED'));
ALTER TABLE accounts ADD COLUMN updated_at TEXT;
UPDATE accounts SET kind = 'local' WHERE id = 'account_local'
"""


def _identity(dialect: str):
    def migrate(conn) -> None:
        _ddl(conn, dialect, _IDENTITY_DDL)
        _append_only(conn, dialect, "platform_role_assignments", "legal_acceptances")
    return migrate


BUNDLE7_MIGRATIONS.append(Migration("023_identity", sqlite=_identity("sqlite"), postgres=_identity("postgres")))


# ---- 024_audit (Task 9): append-only audit log (spec §20.1) -----------------

_AUDIT_DDL = """
CREATE TABLE audit_log (
    {SEQ},
    id TEXT NOT NULL UNIQUE,
    occurred_at TEXT NOT NULL,
    actor_type TEXT NOT NULL CHECK (actor_type IN ('USER', 'STAFF', 'EXTENSION_DEVICE', 'SYSTEM', 'PROVIDER')),
    actor_id TEXT,
    account_id TEXT,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id TEXT,
    request_id TEXT,
    ip_hash TEXT,
    detail_json TEXT NOT NULL
);
CREATE INDEX idx_audit_log_account ON audit_log(account_id, seq);
CREATE INDEX idx_audit_log_action ON audit_log(action, seq)
"""


def _audit(dialect: str):
    def migrate(conn) -> None:
        _ddl(conn, dialect, _AUDIT_DDL)
        _append_only(conn, dialect, "audit_log")
    return migrate


BUNDLE7_MIGRATIONS.append(Migration("024_audit", sqlite=_audit("sqlite"), postgres=_audit("postgres")))


# ---- 025_extension_devices (Task 11): device credentials, pairing codes,
# handoff tickets (spec §9.1). user_id is NULL only in local single-user mode.

_EXTENSION_DDL = """
CREATE TABLE extension_devices (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id),
    user_id TEXT REFERENCES users(id),
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    revoked_at TEXT,
    revoke_reason TEXT
);
CREATE INDEX idx_extension_devices_user ON extension_devices(user_id);
CREATE INDEX idx_extension_devices_account ON extension_devices(account_id);
CREATE TABLE extension_refresh_tokens (
    id TEXT PRIMARY KEY,
    device_id TEXT NOT NULL REFERENCES extension_devices(id),
    family_id TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    issued_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    rotated_at TEXT,
    revoked_at TEXT
);
CREATE INDEX idx_extension_refresh_tokens_device ON extension_refresh_tokens(device_id);
CREATE TABLE extension_access_tokens (
    token_hash TEXT PRIMARY KEY,
    device_id TEXT NOT NULL REFERENCES extension_devices(id),
    expires_at TEXT NOT NULL
);
CREATE INDEX idx_extension_access_tokens_device ON extension_access_tokens(device_id);
CREATE TABLE pairing_codes (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id),
    user_id TEXT REFERENCES users(id),
    code_hash TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    consumed_at TEXT
);
CREATE TABLE handoff_tickets (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id),
    user_id TEXT REFERENCES users(id),
    workspace_id TEXT NOT NULL,
    purpose TEXT NOT NULL CHECK (purpose IN ('HANDOFF')),
    nonce_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    consumed_at TEXT
)
"""


def _extension_devices(dialect: str):
    def migrate(conn) -> None:
        from datetime import datetime, timezone

        _ddl(conn, dialect, _EXTENSION_DDL)
        now = datetime.now(timezone.utc).isoformat()
        # X2: the durable X-Handoff-Credential is retired; every extension pairs again once.
        conn.execute("UPDATE extension_credentials SET revoked_at = ? WHERE revoked_at IS NULL", (now,))
        conn.execute("UPDATE pairing_secrets SET consumed_at = ? WHERE consumed_at IS NULL", (now,))
    return migrate


BUNDLE7_MIGRATIONS.append(Migration("025_extension_devices", sqlite=_extension_devices("sqlite"),
                                    postgres=_extension_devices("postgres")))
