"""Generate webapp/persistence/pg/0001_baseline.sql from a fully migrated
SQLite database (Bundle 7 spec H4/H5, §10.3).

The SQLite schema is read through its catalog (PRAGMA table_info,
foreign_key_list, index_list) rather than by rewriting DDL text, except for
CHECK constraints and trigger bodies, whose text is carried over. Output order:
tables (no foreign keys) -> indexes -> foreign keys -> trigger functions and
triggers. The result is reviewed and committed; the parity test keeps it equal
to the SQLite chain.

Usage: python -m webapp.tools.gen_pg_baseline [--out PATH]
"""
from __future__ import annotations

import argparse
import hashlib
import re
import tempfile
from pathlib import Path

from webapp.persistence.db import connect, init_db
from webapp.persistence.schema_catalog import extract_checks

OUT = Path(__file__).resolve().parents[1] / "persistence" / "pg" / "0001_baseline.sql"
HEADER = """-- GENERATED by webapp/tools/gen_pg_baseline.py from the SQLite chain 001-021.
-- PostgreSQL baseline equal to the post-021 schema (spec H4/H5). Do not edit by
-- hand: regenerate, review, commit. Bundle 7 migrations (022+) are applied on top.
"""
RAISE_FUNCTION = """CREATE FUNCTION jobsearch_raise() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
    RAISE EXCEPTION USING MESSAGE = TG_ARGV[0], ERRCODE = '23000';
END
$fn$;
"""
TRIGGER_RE = re.compile(
    r"CREATE\s+TRIGGER\s+(?P<name>\w+)\s+BEFORE\s+(?P<event>INSERT|DELETE|UPDATE)(?:\s+OF\s+(?P<cols>[\w\s,]+?))?"
    r"\s+ON\s+(?P<table>\w+)\s+(?:WHEN\s+(?P<when>.*?)\s+)?BEGIN\s+SELECT\s+RAISE\(\s*ABORT\s*,\s*'(?P<msg>(?:[^']|'')*)'\s*\)\s*;\s*END",
    re.IGNORECASE | re.DOTALL,
)


def _q(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


GLOBAL_SEED_TABLES = ("discovery_source_settings",)


def _literal(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _column_type(declared: str) -> str:
    declared = (declared or "").upper()
    if declared.startswith("INT"):
        return "BIGINT"
    if declared in ("", "TEXT"):
        return "TEXT"
    if declared == "REAL":
        return "DOUBLE PRECISION"
    if declared == "BLOB":
        return "BYTEA"
    raise ValueError(f"unmapped SQLite type {declared!r}")


def _table_ddl(conn, table: str, create_sql: str) -> list[str]:
    columns = conn.execute(f"PRAGMA table_info({_q(table)})").fetchall()
    pk = [c["name"] for c in sorted(columns, key=lambda c: c["pk"]) if c["pk"]]
    identity = (len(pk) == 1 and next(c for c in columns if c["name"] == pk[0])["type"].upper() == "INTEGER")
    lines = []
    for col in columns:
        if identity and col["name"] == pk[0]:
            lines.append(f"    {_q(col['name'])} BIGINT GENERATED BY DEFAULT AS IDENTITY")
            continue
        parts = [f"    {_q(col['name'])} {_column_type(col['type'])}"]
        if col["notnull"] or col["name"] in pk:
            parts.append("NOT NULL")
        if col["dflt_value"] is not None:
            parts.append(f"DEFAULT {col['dflt_value']}")
        lines.append(" ".join(parts))
    if not identity:
        # SQLite's implicit rowid (insertion order; used by ORDER BY rowid).
        # dbapi hides this column from every result row.
        lines.append('    "rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY')
    lines.append(f"    PRIMARY KEY ({', '.join(_q(c) for c in pk)})") if pk else None
    for index in conn.execute(f"PRAGMA index_list({_q(table)})").fetchall():
        if index["origin"] == "u":
            cols = [r["name"] for r in conn.execute(f"PRAGMA index_info({_q(index['name'])})")]
            lines.append(f"    UNIQUE ({', '.join(_q(c) for c in cols)})")
    for expression in extract_checks(create_sql):
        lines.append(f"    CHECK ({expression})")
    return [f"CREATE TABLE {_q(table)} (\n" + ",\n".join(lines) + "\n);"]


def _foreign_keys(conn, table: str) -> list[str]:
    grouped: dict[int, list] = {}
    for fk in conn.execute(f"PRAGMA foreign_key_list({_q(table)})").fetchall():
        grouped.setdefault(fk["id"], []).append(fk)
    out = []
    for fk_id, rows in sorted(grouped.items()):
        rows.sort(key=lambda r: r["seq"])
        parent = rows[0]["table"]
        local = ", ".join(_q(r["from"]) for r in rows)
        if rows[0]["to"] is None:
            parent_pk = [c["name"] for c in sorted(conn.execute(f"PRAGMA table_info({_q(parent)})").fetchall(),
                                                   key=lambda c: c["pk"]) if c["pk"]]
            remote = ", ".join(_q(c) for c in parent_pk)
        else:
            remote = ", ".join(_q(r["to"]) for r in rows)
        actions = ""
        if rows[0]["on_delete"] and rows[0]["on_delete"] != "NO ACTION":
            actions += f" ON DELETE {rows[0]['on_delete']}"
        if rows[0]["on_update"] and rows[0]["on_update"] != "NO ACTION":
            actions += f" ON UPDATE {rows[0]['on_update']}"
        name = f"fk_{table}_{fk_id}"
        out.append(f"ALTER TABLE {_q(table)} ADD CONSTRAINT {_q(name)} FOREIGN KEY ({local}) "
                   f"REFERENCES {_q(parent)} ({remote}){actions};")
    return out


def _function_name(trigger: str) -> str:
    return f"trgfn_{trigger[:44]}_{hashlib.sha256(trigger.encode()).hexdigest()[:8]}"


def _trigger_ddl(sql: str) -> list[str]:
    match = TRIGGER_RE.search(sql)
    if not match:
        raise ValueError(f"unrecognised trigger shape:\n{sql}")
    name, event, table, msg = match["name"], match["event"].upper(), match["table"], match["msg"]
    cols = match["cols"]
    event_clause = f"UPDATE OF {', '.join(_q(c.strip()) for c in cols.split(','))}" if cols else event
    if match["when"] is None:
        return [f"CREATE TRIGGER {_q(name)} BEFORE {event_clause} ON {_q(table)} "
                f"FOR EACH ROW EXECUTE FUNCTION jobsearch_raise('{msg}');"]
    function = _function_name(name)
    returned = "OLD" if event == "DELETE" else "NEW"
    condition = " ".join(match["when"].split())
    return [
        f"CREATE FUNCTION {function}() RETURNS trigger LANGUAGE plpgsql AS $fn$\n"
        f"BEGIN\n    IF {condition} THEN\n"
        f"        RAISE EXCEPTION USING MESSAGE = '{msg}', ERRCODE = '23000';\n"
        f"    END IF;\n    RETURN {returned};\nEND\n$fn$;",
        f"CREATE TRIGGER {_q(name)} BEFORE {event_clause} ON {_q(table)} "
        f"FOR EACH ROW EXECUTE FUNCTION {function}();",
    ]


def generate(sqlite_path: Path) -> str:
    conn = connect(sqlite_path)
    try:
        objects = conn.execute(
            "SELECT type, name, tbl_name, sql FROM sqlite_master "
            "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY name"
        ).fetchall()
        tables = [o for o in objects if o["type"] == "table"]
        indexes = [o for o in objects if o["type"] == "index"]
        triggers = [o for o in objects if o["type"] == "trigger"]
        out = [HEADER, "-- Tables"]
        for table in tables:
            out.extend(_table_ddl(conn, table["name"], table["sql"]))
        out.append("\n-- Indexes")
        for index in indexes:
            out.append(" ".join(index["sql"].split()) + ";")
        out.append("\n-- Foreign keys")
        for table in tables:
            out.extend(_foreign_keys(conn, table["name"]))
        out.append("\n-- Global seed rows (tables owned by no account)")
        for table in GLOBAL_SEED_TABLES:
            for row in conn.execute(f"SELECT * FROM {_q(table)} ORDER BY 1").fetchall():
                values = ", ".join(_literal(v) for v in row)
                out.append(f"INSERT INTO {_q(table)} ({', '.join(_q(k) for k in row.keys())}) VALUES ({values});")
        out.append("\n-- Triggers")
        out.append(RAISE_FUNCTION)
        for trigger in triggers:
            out.extend(_trigger_ddl(trigger["sql"]))
        return "\n".join(out) + "\n"
    finally:
        conn.close()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "baseline.sqlite3"
        init_db(path)
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(generate(path), encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
