"""Move the local single-user account into a hosted deployment (Bundle 7 spec §23.3).

    python -m webapp.tools.import_local_account --sqlite jobsearch.sqlite3 --profile-root . \\
        --documents-root data/documents --target-dsn postgresql://... \\
        --object-store '{"kind": "s3", "bucket": "...", "endpoint_url": "...", "region": "..."}' \\
        --email founder@example.com --display-name "Founder Name" --assume-verified [--dry-run] [--report PATH]

Steps, in one target transaction:
  1. create the hosted user (ACTIVE, email verified by the operator's
     ``--assume-verified`` assertion; no password: the owner sets one through
     "Forgot password") and a ``candidate`` account with an OWNER membership;
  2. copy every registry table's ``account_local`` rows parents-first,
     re-keying the account id and preserving ids, row order and every hash;
  3. copy each document's bytes (integrity-verified) to the tenant prefix and
     rewrite ``storage_key``;
  4. load the filesystem profile sources into ``profile_source_revisions``;
  5. return (and optionally write) an import report.

It refuses when the target email already exists, so a repeated run changes
nothing. ``--dry-run`` performs every read, check and insert, then rolls the
transaction back and writes no objects."""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from types import SimpleNamespace
from typing import Any

from webapp.persistence import dbapi
from webapp.persistence.tenancy import TENANT_TABLES, owner_chain

__all__ = ["ImportRefused", "ImportReport", "NOT_COPIED", "import_local_account", "main"]

LOCAL_ACCOUNT_ID = "account_local"

# Registry tables whose local rows are deliberately not carried, with the reason.
NOT_COPIED: dict[str, str] = {
    "accounts": "the hosted account is created by the import",
    "account_memberships": "the hosted membership is created by the import",
    # credentials and device bindings: the extension re-pairs once against the hosted origin (spec §3.3)
    "extension_devices": "devices re-pair against the hosted origin",
    "extension_credentials": "credentials are never carried",
    "extension_refresh_tokens": "credentials are never carried",
    "extension_access_tokens": "credentials are never carried",
    "pairing_secrets": "credentials are never carried",
    "pairing_codes": "credentials are never carried",
    "handoff_tickets": "credentials are never carried",
    "handoff_session_tokens": "credentials are never carried",
    # operational state of the local process
    "fill_run_leases": "process leases",
    "jobs": "local worker queue",
    "outbound_messages": "local mail queue",
    "account_exports": "exports point at local objects",
}
_IDENTITY_COLUMNS = ("seq", "rowid")  # regenerated by the target in source order


class ImportRefused(Exception):
    def __init__(self, code: str, message: str) -> None:
        super().__init__(f"{code}: {message}")
        self.code, self.message = code, message


@dataclass
class ImportReport:
    account_id: str
    user_id: str
    email: str
    dry_run: bool
    copied: dict[str, int] = field(default_factory=dict)
    not_copied: dict[str, int] = field(default_factory=dict)
    blobs: int = 0
    profile_sources: list[str] = field(default_factory=list)
    started_at: str = ""
    finished_at: str = ""


def _source_tables(source: Any, target: Any) -> list[str]:
    """Account-owned registry tables, parents before children."""
    from webapp.persistence.schema_catalog import schema_catalog
    from webapp.services.purge import purge_sequence

    target_catalog = schema_catalog(target)
    source_catalog = schema_catalog(source)
    tables = []
    for table in reversed(purge_sequence(source)):
        if owner_chain(table)[-1][2] == "USER":
            continue  # user-keyed: the local account has no users
        missing = {c[0] for c in source_catalog[table]["columns"]} - {
            c[0] for c in target_catalog.get(table, {}).get("columns", ())}
        if table not in target_catalog or missing:
            raise ImportRefused("SCHEMA_MISMATCH", f"{table} differs in the target ({sorted(missing)})")
        tables.append(table)
    return tables


def _columns(catalog_entry: Any) -> list[str]:
    return [c[0] for c in catalog_entry["columns"] if c[0] not in _IDENTITY_COLUMNS]


def _check_target(target: Any, email_normalized: str) -> None:
    from webapp.persistence.bundle7_migrations import BUNDLE7_MIGRATIONS
    from webapp.persistence.migrations import LEGACY_MIGRATION_IDS

    applied = {r[0] for r in target.execute("SELECT id FROM schema_migrations").fetchall()}
    missing = (set(LEGACY_MIGRATION_IDS) | {m.id for m in BUNDLE7_MIGRATIONS}) - applied
    if missing:
        raise ImportRefused("TARGET_NOT_MIGRATED", f"the target lacks migrations {sorted(missing)}")
    if target.execute("SELECT 1 FROM users WHERE email_normalized = ?", (email_normalized,)).fetchone():
        raise ImportRefused("EMAIL_EXISTS", "a user with this email already exists in the target")


def import_local_account(*, sqlite_path: Path, profile_root: Path, documents_root: Path, target_dsn: str,
                         object_store: Any, email: str, display_name: str, assume_verified: bool,
                         dry_run: bool = False, now: datetime | None = None) -> ImportReport:
    from product.profile_snapshot import SOURCE_PATHS, FilesystemSourceReader
    from webapp.persistence.audit import audit
    from webapp.persistence.identity import normalize_email
    from webapp.persistence.schema_catalog import schema_catalog
    from webapp.services.document_blob_store import DocumentBlobStore
    from webapp.services.purge import account_filter
    from webapp.storage.profile_sources import DatabaseProfileSources

    if not assume_verified:
        raise ImportRefused("VERIFICATION_NOT_ASSERTED",
                            "pass --assume-verified to assert that the operator verified this email")
    if not str(target_dsn).startswith("postgresql://"):
        raise ImportRefused("TARGET_NOT_HOSTED", "the target must be a postgresql:// database")
    sqlite_path = Path(sqlite_path)
    if not sqlite_path.is_file():
        raise ImportRefused("SOURCE_MISSING", f"no SQLite database at {sqlite_path}")
    now = now or datetime.now(timezone.utc)
    stamp = now.isoformat()
    email_normalized = normalize_email(email)
    name = " ".join((display_name or "").split())
    if not name:
        raise ImportRefused("NAME_REQUIRED", "a display name is required")

    source = dbapi._connect_sqlite(sqlite_path)  # never redirected: the source is the local file
    target = dbapi.connect(target_dsn)
    try:
        if source.execute("SELECT 1 FROM accounts WHERE id = ?", (LOCAL_ACCOUNT_ID,)).fetchone() is None:
            raise ImportRefused("SOURCE_HAS_NO_LOCAL_ACCOUNT", "the source has no account_local")
        _check_target(target, email_normalized)
        tables = _source_tables(source, target)
        source_catalog = schema_catalog(source)
        account_id = f"account_{uuid.uuid4().hex[:20]}"
        user_id = f"user_{uuid.uuid4().hex[:20]}"
        report = ImportReport(account_id=account_id, user_id=user_id, email=email_normalized, dry_run=dry_run,
                              started_at=stamp)
        local_blobs = DocumentBlobStore(Path(documents_root))
        hosted_blobs = DocumentBlobStore(object_store)
        pending_objects: dict[str, bytes] = {}

        with dbapi.account_transaction(target, account_id):
            # 1. the hosted user and account
            target.execute(
                "INSERT INTO users (id, email_normalized, email_display, display_name, status, email_verified_at, "
                "created_at, updated_at) VALUES (?, ?, ?, ?, 'ACTIVE', ?, ?, ?)",
                (user_id, email_normalized, email.strip(), name, stamp, stamp, stamp))
            target.execute("INSERT INTO accounts (id, display_name, created_at, kind, status, updated_at) "
                           "VALUES (?, ?, ?, 'candidate', 'ACTIVE', ?)", (account_id, name, stamp, stamp))
            target.execute("INSERT INTO account_memberships (account_id, user_id, role, created_at) "
                           "VALUES (?, ?, 'OWNER', ?)", (account_id, user_id, stamp))

            # 2-3. every owned table, parents first, in source row order
            for table in tables:
                where, params = account_filter(table, LOCAL_ACCOUNT_ID, [])
                rows = source.execute(f'SELECT * FROM "{table}" WHERE {where} ORDER BY rowid',
                                      tuple(params)).fetchall()
                if table in NOT_COPIED:
                    if rows:
                        report.not_copied[table] = len(rows)
                    continue
                columns = _columns(source_catalog[table])
                insert = (f'INSERT INTO "{table}" ({", ".join(chr(34) + c + chr(34) for c in columns)}) '
                          f'VALUES ({", ".join("?" for _ in columns)})')
                for row in rows:
                    values = {c: (account_id if row[c] == LOCAL_ACCOUNT_ID else row[c]) for c in columns}
                    if table == "application_document_versions":
                        content = local_blobs.read({"storage_key": row["storage_key"],
                                                    "byte_length": row["byte_length"], "sha256": row["sha256"]})
                        from webapp.storage.object_store import tenant_document_key
                        key = tenant_document_key(account_id, row["sha256"], row["media_type"])
                        values["storage_key"] = key
                        pending_objects[key] = content
                    target.execute(insert, tuple(values[c] for c in columns))
                report.copied[table] = len(rows)
            report.blobs = len(pending_objects)

            # 4. the filesystem profile sources, as the snapshot reads them (universal newlines)
            reader = FilesystemSourceReader(Path(profile_root))
            sources = DatabaseProfileSources(target, account_id)
            for source_path in SOURCE_PATHS:
                text = reader.read(source_path)
                if text is not None and sources.read(source_path) != text:
                    sources.write(source_path, text)
                    report.profile_sources.append(source_path)

            audit(target, actor_type="SYSTEM", actor_id="import_local_account", account_id=account_id,
                  action="ACCOUNT_IMPORTED", now=now, target_type="account", target_id=account_id,
                  detail={"tables": len(report.copied), "rows": sum(report.copied.values()), "blobs": report.blobs})

            if dry_run:
                raise _DryRunRollback()
            # objects before the commit: an object without rows is harmless (write-once, tenant-prefixed),
            # rows without their object are not
            for key, content in pending_objects.items():
                object_store.put(key, content)
                hosted_blobs.read({"storage_key": key, "byte_length": len(content),
                                   "sha256": hashlib.sha256(content).hexdigest()})
    except _DryRunRollback:
        pass
    finally:
        source.close()
        target.close()
    report.finished_at = datetime.now(timezone.utc).isoformat()
    return report


class _DryRunRollback(Exception):
    """Raised inside the target transaction so account_transaction rolls it back."""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--sqlite", required=True, type=Path)
    parser.add_argument("--profile-root", required=True, type=Path)
    parser.add_argument("--documents-root", required=True, type=Path)
    parser.add_argument("--target-dsn", required=True)
    parser.add_argument("--object-store", required=True,
                        help='JSON, as JOBSEARCH_OBJECT_STORE: {"kind": "s3", ...} or {"kind": "local", "root": ...}')
    parser.add_argument("--email", required=True)
    parser.add_argument("--display-name", required=True)
    parser.add_argument("--assume-verified", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--report", type=Path)
    args = parser.parse_args(argv)
    from webapp.storage.object_store import object_store_from_settings

    try:
        config = json.loads(args.object_store)
    except ValueError:
        parser.error("--object-store must be JSON")
    store = object_store_from_settings(SimpleNamespace(object_store=config, documents_root=args.documents_root))
    try:
        report = import_local_account(sqlite_path=args.sqlite, profile_root=args.profile_root,
                                      documents_root=args.documents_root, target_dsn=args.target_dsn,
                                      object_store=store, email=args.email, display_name=args.display_name,
                                      assume_verified=args.assume_verified, dry_run=args.dry_run)
    except ImportRefused as refused:
        print(f"Import refused: {refused}", file=sys.stderr)
        return 1
    text = json.dumps(asdict(report), indent=1, sort_keys=True)
    if args.report:
        args.report.write_text(text, encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
