"""Closed vocabulary for audit_log (Bundle 7 spec §20.1)."""
from __future__ import annotations

ACTOR_TYPES = frozenset({"USER", "STAFF", "EXTENSION_DEVICE", "SYSTEM", "PROVIDER"})

AUDIT_ACTIONS = frozenset({
    "LOGIN_SUCCEEDED", "LOGIN_FAILED", "LOGOUT", "SESSIONS_REVOKED",
    "PASSWORD_CHANGED", "PASSWORD_RESET", "EMAIL_VERIFIED", "EMAIL_CHANGED",
    "EXTENSION_DEVICE_PAIRED", "EXTENSION_DEVICE_REVOKED", "EXTENSION_TOKEN_REUSE",
    "PLAN_CHECKOUT_STARTED", "SUBSCRIPTION_STATE_CHANGED",
    "ENTITLEMENT_GRANT_CREATED", "ENTITLEMENT_GRANT_REVOKED",
    "ACCOUNT_SUSPENDED", "ACCOUNT_UNSUSPENDED", "ACCOUNT_DELETION_REQUESTED", "ACCOUNT_DELETION_CANCELED",
    "ACCOUNT_PURGED",
    "DATA_EXPORT_REQUESTED", "DATA_EXPORT_DOWNLOADED",
    "PLATFORM_CONTROL_SET", "STAFF_ROLE_CHANGED", "ANNOUNCEMENT_PUBLISHED",
    "ADMIN_ACCOUNT_VIEWED", "DEAD_LETTER_RETRIED",
    "CONSENT_CHANGED",
})
