"""Bundle 6D-B closed vocabularies (spec §11.1, §11.3, §14, §15, §19). One
source of truth: migration 020_fill builds its CHECK constraints from these
tuples, and the services use the same names. None contains a release or
submit value."""
from __future__ import annotations

# Run lifecycle (spec §11.1). FILLED_CONTEXT_UNVERIFIED is recorded by the
# lease reaper after FILLED_AWAITING_SUBMISSION when continuity is lost.
RUN_EVENTS = (
    "OBSERVING", "PLAN_PROPOSED", "PLAN_NEEDS_REVIEW", "UNSUPPORTED_FORM", "REVALIDATING", "QUARANTINE_ACTIVE",
    "FILLING", "FINAL_VALIDATING", "FILLED_AWAITING_SUBMISSION", "FILL_STOPPED", "FILLED_CONTEXT_UNVERIFIED",
)
# A terminal run releases its active_fill_runs slot. A FILLED run keeps its
# lease (heartbeats) so continuity of the quarantined page stays provable.
TERMINAL_RUN_EVENTS = ("PLAN_NEEDS_REVIEW", "UNSUPPORTED_FORM", "FILL_STOPPED", "FILLED_AWAITING_SUBMISSION")

# spec §14, closed. UNSUPPORTED_FORM is both a state and a stop reason
# (detail.cause carries one of UNSUPPORTED_CAUSES).
STOP_REASONS = (
    "DELTA_OPENED", "UNSUPPORTED_FORM", "STRUCTURE_CHANGED", "STRUCTURE_UNSTABLE", "OBSERVATION_MISMATCH",
    "OMIT_FIELD_NOT_BLANK", "PREFILLED_VALUE_CONFLICT", "TARGET_CHANGED", "READBACK_MISMATCH",
    "FIELD_VALIDITY_FAILED", "FIELD_VALUE_REVERTED", "ATTACH_LOCAL_MISMATCH", "SIBLING_EMPLOYER_CONTEXT_OPEN",
    "PERMISSIONS_MISSING", "QUARANTINE_RULESET_CHANGED", "QUARANTINE_LOST", "SUBMIT_ATTEMPT_OBSERVED",
    "NAVIGATION_ATTEMPT_OBSERVED", "GRANT_REFUSED", "GRANT_EXPIRED", "AUTHORITY_REDUCED", "APPROVAL_NOT_EFFECTIVE",
    "PLAN_CONFIRMATION_STALE", "ENVELOPE_EXPIRED", "WRITE_OUTCOME_UNKNOWN", "EXECUTOR_LOST",
    "EXECUTION_CONTEXT_CLOSED",
)
UNSUPPORTED_CAUSES = (
    "MULTI_STEP", "UNCERTIFIED_ADAPTER", "NO_APPLICATION_ROOT", "CROSS_ORIGIN_APPLICATION_FRAME",
    "AMBIGUOUS_FIELD_IDENTITY", "UNSUPPORTED_REQUIRED_WIDGET", "RESET_SURFACE_MISMATCH",
)
AUTHORITY_REDUCTIONS = ("PAUSED", "KILL_SWITCH", "CEILING", "POLICY")

ACTION_KINDS = ("WRITE", "ATTACH_LOCAL", "OMIT", "IGNORE_NON_APPLICATION")
MAPPING_BASES = ("ADAPTER_RULE", "USER_CONFIRMED", "NON_APPLICATION_PROOF")
NON_APPLICATION_PROOFS = ("OUTSIDE_APPLICATION_ROOT", "ADAPTER_NON_APPLICATION_RULE", "SUBMIT_CLASS_CONTROL")

ACTION_EVENTS = ("PRECHECK", "WRITE_INTENT", "ENVELOPE_ISSUED", "OUTCOME")
# Terminal per-action outcomes (spec §11.3 d); at most one per action.
SUCCESS_OUTCOMES = ("WRITTEN_VERIFIED", "NOOP_ALREADY_EQUAL", "OMIT_VERIFIED", "IGNORE_RECORDED",
                    "ATTACH_LOCAL_VERIFIED")
FAILURE_OUTCOMES = ("READBACK_MISMATCH", "TARGET_CHANGED", "FIELD_VALIDITY_FAILED", "FIELD_VALUE_REVERTED",
                    "ATTACH_LOCAL_MISMATCH", "WRITE_OUTCOME_UNKNOWN", "ENVELOPE_EXPIRED")
ACTION_OUTCOMES = SUCCESS_OUTCOMES + FAILURE_OUTCOMES

OBSERVATION_PHASES = ("INITIAL", "REVALIDATION", "PRE_ACTION", "POST_ACTION", "FINAL", "POST_FILL")
QUARANTINE_PHASES = ("PRELOAD_INSTALLED", "RELOADED", "TOTAL_VERIFIED", "VERIFIED_BEFORE_ACTION", "LOST")
DETECTION_KINDS = ("SUBMIT_ATTEMPT_OBSERVED", "NAVIGATION_ATTEMPT_OBSERVED", "POST_FILL_CHANGE_OBSERVED",
                   "EXECUTION_CONTEXT_CLOSED")
MAPPING_CHOICES = ("MAP", "NEW_QUESTION")
PROPOSAL_BASES = ("HEURISTIC", "MODEL")


def sql_in(values: tuple[str, ...]) -> str:
    """A SQL IN-list literal for a CHECK constraint (values are fixed identifiers)."""
    for value in values:
        if not value.replace("_", "").isalnum() or not value.isupper():
            raise ValueError(f"not a vocabulary identifier: {value!r}")
    return ", ".join(f"'{value}'" for value in values)
